"""add_timestamps_soft_delete_and_security_models

Revision ID: 9c873cfcb3dd
Revises: 15ae9fa2ed3d
Create Date: 2026-02-09 09:02:52.935880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c873cfcb3dd'
down_revision: Union[str, Sequence[str], None] = '15ae9fa2ed3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblacklist',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenblacklist_token'), 'tokenblacklist', ['token'], unique=True)
    op.create_table('auditlog',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_resource_type'), 'auditlog', ['resource_type'], unique=False)
    
    # Add columns with server defaults for existing rows
    op.add_column('course', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('course', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    
    op.add_column('enrollment', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('enrollment', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('enrollment', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    
    op.add_column('lesson', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('lesson', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('lesson', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    
    op.add_column('payment', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('payment', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    
    op.add_column('profile', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('profile', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('profile', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(), nullable=True))
    
    op.add_column('vehicle', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('vehicle', sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('vehicle', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'updated_at')
    op.drop_column('vehicle', 'created_at')
    op.drop_column('vehicle', 'deleted_at')
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'deleted_at')
    op.drop_column('profile', 'updated_at')
    op.drop_column('profile', 'created_at')
    op.drop_column('profile', 'deleted_at')
    op.drop_column('payment', 'updated_at')
    op.drop_column('payment', 'created_at')
    op.drop_column('payment', 'deleted_at')
    op.drop_column('lesson', 'updated_at')
    op.drop_column('lesson', 'created_at')
    op.drop_column('lesson', 'deleted_at')
    op.drop_column('enrollment', 'updated_at')
    op.drop_column('enrollment', 'created_at')
    op.drop_column('enrollment', 'deleted_at')
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'created_at')
    op.drop_column('course', 'deleted_at')
    op.drop_index(op.f('ix_auditlog_resource_type'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_tokenblacklist_token'), table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    # ### end Alembic commands ###
