"""add_settings_table

Revision ID: bd7207b74794
Revises: d025997d1c95
Create Date: 2026-02-11 20:26:40.188759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd7207b74794'
down_revision: Union[str, Sequence[str], None] = 'd025997d1c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sqlmodel.sql.sqltypes.AutoString(length=100), server_default='IDSMS', nullable=False),
    sa.Column('school_tagline', sqlmodel.sql.sqltypes.AutoString(length=200), server_default='Inphora Driving School Management System', nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=7), server_default='#3b82f6', nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), server_default='Africa/Nairobi', nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), server_default='KES', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Fill existing nulls in profile table
    op.execute("UPDATE profile SET first_name = 'Unknown' WHERE first_name IS NULL")
    op.execute("UPDATE profile SET last_name = 'Unknown' WHERE last_name IS NULL")

    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profile', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profile', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('settings')
    # ### end Alembic commands ###
