"""Add_Kenyan_Features_and_Curriculum

Revision ID: d025997d1c95
Revises: 15a1bcffee82
Create Date: 2026-02-11 19:21:40.661726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd025997d1c95'
down_revision: Union[str, Sequence[str], None] = '15a1bcffee82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_name'), 'curriculum', ['name'], unique=False)
    op.create_table('module',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('curriculum_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('module_type', sa.Enum('THEORY', 'PRACTICAL', 'TEST_PREP', name='moduletype'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessontopic',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentprogress',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('instructor_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['lessontopic.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings')
    op.add_column('assessment', sa.Column('booking_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assessment', sa.Column('test_center', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profile', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profile', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profile', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('profile', sa.Column('pdl_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profile', sa.Column('pdl_issue_date', sa.Date(), nullable=True))
    op.add_column('profile', sa.Column('pdl_expiry_date', sa.Date(), nullable=True))
    op.add_column('profile', sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profile', sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'emergency_contact_phone')
    op.drop_column('profile', 'emergency_contact_name')
    op.drop_column('profile', 'pdl_expiry_date')
    op.drop_column('profile', 'pdl_issue_date')
    op.drop_column('profile', 'pdl_number')
    op.drop_column('profile', 'date_of_birth')
    op.drop_column('profile', 'last_name')
    op.drop_column('profile', 'first_name')
    op.drop_column('assessment', 'test_center')
    op.drop_column('assessment', 'booking_reference')
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('school_tagline', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('settings_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey'))
    )
    op.drop_table('studentprogress')
    op.drop_table('lessontopic')
    op.drop_table('module')
    op.drop_index(op.f('ix_curriculum_name'), table_name='curriculum')
    op.drop_table('curriculum')
    # ### end Alembic commands ###
